# Generated by Django 6.0.7 on 2026-08-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('applied_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
