# Generated by Django 6.0.7 on 2026-08-16 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_date',
            new_name='date_applied',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='job_title',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
